version: '3'

services:
  warp:
    image: ghcr.io/j4mez/warp-proxy:sha256-5fb9714a2c893451e51ae3125c4d30e6e1ee1a2690c0705d710b06b60eca08cd.sig
    container_name: warp
    restart: always
    ports:
      - '1080:1080'
    environment:
      - WARP_SLEEP=2
      # - WARP_LICENSE_KEY= # optional
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./data:/var/lib/cloudflare-warp
